name: Build Test

on:
  push:
    branches:
      - main
      - dev
      - release*
      - prepare-for-open-source
  pull_request:
    branches:
      - main
      - dev
      - release*

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install CUDA 12.1
        run: |
          bash -x .github/workflows/scripts/cuda-install.sh 12.1 ubuntu-20.04

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build Wheel
        run: |
          BUILD_OPS=1 python3 -m build
